package com.dis.fshipbot;

import com.dis.fshipbot.config.GlobalViewAdvice;
import com.dis.fshipbot.config.PageAccessInterceptor;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The admin panel's branding comes from {@code application.title}, not from
 * text typed into a template.
 *
 * <p>{@code application.title=@project.name@} is Maven-filtered from the POM,
 * so a rename in pom.xml propagates everywhere. A hard-coded string in a
 * template would silently keep the old name, and nothing would fail — the page
 * would just be wrong. These tests fail on the literal instead.
 */
@SpringBootTest(properties = {
        "app.ingestion.run-on-startup=false",
        // A deliberately distinctive value: if a template still holds a literal,
        // the rendered page will not contain this.
        "application.title=Branding Probe",
        "application.version=9.9.9",
        "spring.datasource.url=jdbc:h2:mem:branding;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none"
})
@AutoConfigureMockMvc
class AdminBrandingTest {

    @MockBean
    private EmbeddingStore<TextSegment> embeddingStore;

    @MockBean
    private EmbeddingModel embeddingModel;

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private GlobalViewAdvice advice;

    @Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbc;

    @BeforeEach
    void createSchema() {
        // The settings page reads app_setting/app_suggestion, which H2 does not
        // have. Empty tables are enough: this test is about the brand name, not
        // the data behind it.
        jdbc.execute("DROP SCHEMA IF EXISTS fship_ai CASCADE");
        jdbc.execute("CREATE SCHEMA IF NOT EXISTS fship_ai");
        jdbc.execute("CREATE TABLE fship_ai.app_setting ("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "config_key varchar(100) NOT NULL UNIQUE, "
                + "config_value text NOT NULL DEFAULT '', "
                + "category varchar(50) NOT NULL DEFAULT 'general', "
                + "updated_at timestamp DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE fship_ai.app_suggestion ("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "question text NOT NULL, caption text NOT NULL DEFAULT '', "
                + "icon varchar(10) DEFAULT '', sort_order int4 DEFAULT 0, "
                + "is_active boolean DEFAULT true, "
                + "created_at timestamp DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at timestamp DEFAULT CURRENT_TIMESTAMP)");
    }

    @Value("${application.title}")
    private String title;

    @Value("${application.version}")
    private String version;

    private static MockHttpSession adminSession() {
        MockHttpSession s = new MockHttpSession();
        s.setAttribute(PageAccessInterceptor.SESSION_KEY, true);
        return s;
    }

    private String render(String path) throws Exception {
        MvcResult result = mockMvc.perform(get(path).session(adminSession()))
                .andExpect(status().isOk())
                .andReturn();
        return result.getResponse().getContentAsString();
    }

    @Test
    void adviceExposesTheConfiguredName() {
        Assertions.assertEquals("Branding Probe", advice.appName());
        Assertions.assertEquals("9.9.9", advice.appVersion());
    }

    @Test
    void propertiesAreTheSourceOfTheName() {
        // Guards the wiring itself: if application.title were ever removed from
        // application.properties, the advice would silently fall back.
        Assertions.assertEquals("Branding Probe", title);
    }

    @Test
    void loginPageShowsTheConfiguredName() throws Exception {
        String html = render("/admin/login");
        Assertions.assertTrue(html.contains("Branding Probe"),
                "the admin login header must render application.title, not a literal");
    }

    @Test
    void everyAdminPageShowsTheConfiguredName() throws Exception {
        for (String path : List.of("/admin/prompts", "/admin/settings", "/admin/documents")) {
            String html = render(path);
            Assertions.assertTrue(html.contains("Branding Probe"),
                    path + " must render the sidebar brand from application.title");
            Assertions.assertTrue(html.contains("<title>Branding Probe"),
                    path + " must title itself from application.title");
        }
    }

    @Test
    void noTemplateHardcodesTheOldBrand() throws IOException {
        // PromptDefaults legitimately contains the phrase in prompt TEXT; this
        // check is about branding markup in templates only.
        Path templates = Paths.get("src", "main", "resources", "templates");
        try (java.util.stream.Stream<Path> files = Files.walk(templates)) {
            files.filter(Files::isRegularFile)
                    .filter(p -> p.toString().endsWith(".html"))
                    .forEach(p -> {
                        try {
                            String content = new String(Files.readAllBytes(p), StandardCharsets.UTF_8);
                            Assertions.assertFalse(content.contains("Friendship AI"),
                                    p + " hard-codes the brand name; use ${appName} so the "
                                            + "name follows application.title");
                        } catch (IOException e) {
                            throw new java.io.UncheckedIOException(e);
                        }
                    });
        }
    }
}
