package com.dis.fshipbot;

import com.dis.fshipbot.model.AppPrompt;
import com.dis.fshipbot.repository.AppPromptRepository;
import com.dis.fshipbot.service.PromptService;
import com.dis.fshipbot.util.PromptDefaults;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.Collections;
import java.util.List;

import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The admin save path against a real database.
 *
 * <p>Every other prompt test uses a mocked {@code JdbcTemplate}, which cannot
 * catch the failures that actually break an edit in production: a table that was
 * never created, a column name that does not exist, a seed that inserted nothing,
 * or a write that commits and then reads back blank. Here the {@code app_prompt}
 * table is created and seeded exactly as {@code db/schema.sql} +
 * {@code db/data.sql} do it, so a drift between those scripts and the
 * repository shows up as a failing test rather than a 400 in the browser.
 */
@SpringBootTest(properties = {
        "app.ingestion.run-on-startup=false",
        "spring.datasource.url=jdbc:h2:mem:promptrepo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@AutoConfigureMockMvc
class PromptPersistenceIT {

    // The pgvector store cannot start on H2 (it issues SET ivfflat.probes, which
    // only PostgreSQL understands). These are not under test here.
    @MockBean
    private EmbeddingStore<TextSegment> embeddingStore;

    @MockBean
    private EmbeddingModel embeddingModel;

    @Autowired
    private AppPromptRepository repo;

    @Autowired
    private PromptService promptService;

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbc;

    private MockHttpSession adminSession;

    @org.junit.jupiter.api.BeforeEach
    void seedAndLogin() {
        seedTable();
        promptService.reload();
        adminSession = new MockHttpSession();
        adminSession.setAttribute(
                com.dis.fshipbot.config.PageAccessInterceptor.SESSION_KEY, true);
    }

    @BeforeEach
    void setUp() {
        seedTable();
    }

    private void seedTable() {
        // Mirrors db/schema.sql, including the schema qualifier the repository
        // hard-codes. Kept in code (not a script run) so the test is
        // self-contained and still exercises the repository's real SQL.
        jdbc.execute("DROP SCHEMA IF EXISTS fship_ai CASCADE");
        jdbc.execute("CREATE SCHEMA IF NOT EXISTS fship_ai");
        jdbc.execute("CREATE TABLE fship_ai.app_prompt ("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "prompt_key varchar(100) NOT NULL UNIQUE, "
                + "prompt_group varchar(50) NOT NULL DEFAULT 'chat', "
                + "label varchar(200) NOT NULL DEFAULT '', "
                + "description text NOT NULL DEFAULT '', "
                + "placeholders varchar(200) NOT NULL DEFAULT '', "
                + "content text NOT NULL DEFAULT '', "
                + "sort_order int4 DEFAULT 0, "
                + "updated_at timestamp DEFAULT CURRENT_TIMESTAMP)");

        for (PromptDefaults.PromptDef def : PromptDefaults.all()) {
            String ph = String.join(",", def.getPlaceholders());
            jdbc.update("INSERT INTO fship_ai.app_prompt "
                            + "(prompt_key, prompt_group, label, description, placeholders, content, sort_order) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    def.getKey(), def.getGroup(), def.getLabel(),
                    def.getDescription(), ph, def.getDefaultText(), 0);
        }
    }

    @Test
    void everyRegistryPromptHasExactlyOneSeededRow() {
        Assertions.assertEquals(PromptDefaults.all().size(), repo.count(),
                "data.sql must seed one row per registry prompt, or an edit to a "
                        + "missing prompt silently fails");
    }

    @Test
    void findAllReturnsTheSeededContentVerbatim() {
        List<AppPrompt> rows = repo.findAll();

        Assertions.assertEquals(PromptDefaults.all().size(), rows.size());
        AppPrompt system = rows.stream()
                .filter(p -> PromptDefaults.SYSTEM.equals(p.getKey()))
                .findFirst()
                .orElseThrow(AssertionError::new);

        // Whitespace is meaningful in these prompts; a trim or a lossy mapping
        // here would change what the model receives.
        Assertions.assertEquals(PromptDefaults.defaultText(PromptDefaults.SYSTEM), system.getContent());
        Assertions.assertEquals(List.of("{context}"), system.getPlaceholders());
        Assertions.assertEquals("chat", system.getGroup());
    }

    @Test
    void savePersistsAndReadsBack() {
        repo.save(PromptDefaults.SYSTEM, "MY REPLACED SYSTEM PROMPT");

        String stored = jdbc.queryForObject(
                "SELECT content FROM fship_ai.app_prompt WHERE prompt_key = ?",
                String.class, PromptDefaults.SYSTEM);

        Assertions.assertEquals("MY REPLACED SYSTEM PROMPT", stored,
                "the edit must be in the database, not just returned to the caller");
        Assertions.assertEquals("MY REPLACED SYSTEM PROMPT", repo.findByKey(PromptDefaults.SYSTEM).getContent());
    }

    @Test
    void saveIsVisibleToFindAllSoTheAdminGridReflectsIt() {
        repo.save(PromptDefaults.CASUAL, "edited casual prompt");

        AppPrompt casual = repo.findAll().stream()
                .filter(p -> PromptDefaults.CASUAL.equals(p.getKey()))
                .findFirst()
                .orElseThrow(AssertionError::new);

        Assertions.assertEquals("edited casual prompt", casual.getContent());
    }

    @Test
    void saveStampsUpdatedAt() throws InterruptedException {
        jdbc.update("UPDATE fship_ai.app_prompt SET updated_at = timestamp '2000-01-01 00:00:00' "
                + "WHERE prompt_key = ?", PromptDefaults.SYSTEM);
        AppPrompt before = repo.findByKey(PromptDefaults.SYSTEM);

        Thread.sleep(1100);
        repo.save(PromptDefaults.SYSTEM, "touched");

        AppPrompt after = repo.findByKey(PromptDefaults.SYSTEM);
        Assertions.assertNotEquals(before.getUpdatedAt(), after.getUpdatedAt(),
                "an edit with no new timestamp cannot be shown as 'updated' in the admin UI");
    }

    @Test
    void savePreservesMultilineTextAndPlaceholders() {
        String multi = "Line one\n\nLine two with {context} inside\n\"quoted\", 'single' -- dashes";
        repo.save(PromptDefaults.SYSTEM, multi);

        Assertions.assertEquals(multi, repo.findByKey(PromptDefaults.SYSTEM).getContent());
    }

    @Test
    void saveOnAMissingKeyIsANoOpRatherThanAnInsert() {
        long before = repo.count();
        repo.save("prompt.invented", "text");

        Assertions.assertEquals(before, repo.count(),
                "prompts are seeded by data.sql; the app must never insert them");
        Assertions.assertNull(repo.findByKey("prompt.invented"));
    }

    @Test
    void savingOnePromptLeavesTheOthersUntouched() {
        String casualBefore = repo.findByKey(PromptDefaults.CASUAL).getContent();

        repo.save(PromptDefaults.SYSTEM, "only the system prompt changes");

        Assertions.assertEquals(casualBefore, repo.findByKey(PromptDefaults.CASUAL).getContent(),
                "an edit must not leak into sibling prompts");
    }

    // ---- The service cache: an edit must be what the chat pipeline reads ----

    @Test
    void serviceServesTheEditedTextNotTheDefault() {
        Assertions.assertEquals(PromptDefaults.defaultText(PromptDefaults.SYSTEM),
                promptService.get(PromptDefaults.SYSTEM));

        promptService.save(PromptDefaults.SYSTEM, "EDITED VIA THE SERVICE");

        Assertions.assertEquals("EDITED VIA THE SERVICE", promptService.get(PromptDefaults.SYSTEM),
                "the cache must serve the edit immediately — this is the text the model receives");
    }

    @Test
    void serviceRendersPlaceholdersFromTheEditedText() {
        promptService.save(PromptDefaults.SYSTEM, "context was: {context}");

        String rendered = promptService.render(PromptDefaults.SYSTEM,
                Collections.singletonMap("context", "LEAVE POLICY"));

        Assertions.assertEquals("context was: LEAVE POLICY", rendered);
    }

    @Test
    void serviceFlagsTheEditedPromptAsCustomized() {
        promptService.save(PromptDefaults.CASUAL, "a custom casual prompt");

        AppPrompt casual = promptService.listAll().stream()
                .filter(p -> PromptDefaults.CASUAL.equals(p.getKey()))
                .findFirst()
                .orElseThrow(AssertionError::new);

        Assertions.assertTrue(casual.isCustomized(),
                "the admin grid badges edited prompts; this drives that badge");
        Assertions.assertEquals("a custom casual prompt", casual.getContent());
    }

    @Test
    void serviceRejectsAKeyThatIsNotInTheRegistry() {
        Assertions.assertThrows(IllegalArgumentException.class,
                () -> promptService.save("prompt.invented", "text"),
                "only registry keys are writable");
    }

    @Test
    void serviceRejectsAnEditWhenTheRowIsMissingFromTheDatabase() {
        // A registry key whose row was never seeded: the UPDATE would match zero
        // rows and the edit would vanish, so the save must refuse instead.
        jdbc.update("DELETE FROM fship_ai.app_prompt WHERE prompt_key = ?", PromptDefaults.CASUAL);
        Assertions.assertNull(repo.findByKey(PromptDefaults.CASUAL));

        IllegalStateException e = Assertions.assertThrows(IllegalStateException.class,
                () -> promptService.save(PromptDefaults.CASUAL, "text"),
                "an edit to a missing row must fail loudly rather than silently no-op");
        Assertions.assertTrue(e.getMessage().contains("data.sql"),
                "the message must name the script to run: " + e.getMessage());
    }

    // ---- The HTTP path the admin page actually calls ----

    @Test
    void adminSaveEndpointWritesToTheDatabase() throws Exception {
        mockMvc.perform(post("/admin/api/prompts")
                        .session(adminSession)
                        .contentType("application/json")
                        .content("{\"key\":\"" + PromptDefaults.SYSTEM + "\","
                                + "\"content\":\"EDITED OVER HTTP\"}"))
                .andExpect(status().isOk());

        Assertions.assertEquals("EDITED OVER HTTP",
                jdbc.queryForObject(
                        "SELECT content FROM fship_ai.app_prompt WHERE prompt_key = ?",
                        String.class, PromptDefaults.SYSTEM),
                "the browser's save must land in the database");
        Assertions.assertEquals("EDITED OVER HTTP", promptService.get(PromptDefaults.SYSTEM));
    }

    @Test
    void adminListEndpointReturnsTheCurrentText() throws Exception {
        promptService.save(PromptDefaults.NO_CONTEXT, "no context, sorry");

        mockMvc.perform(get("/admin/api/prompts").session(adminSession))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.prompts[?(@.key=='prompt.no_context')].content")
                        .value("no context, sorry"));
    }

    @Test
    void adminSaveEndpointRejectsAnUnknownKey() throws Exception {
        mockMvc.perform(post("/admin/api/prompts")
                        .session(adminSession)
                        .contentType("application/json")
                        .content("{\"key\":\"prompt.invented\",\"content\":\"x\"}"))
                .andExpect(status().isBadRequest());
    }
}
